baseURL = "http://pols1600.github.io"
languageCode = "en-us"
title = "POLS 1600"
theme = "minimal"
pluralizelisttitles = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    author = "Danilo Freire"
    description = "Course website for POLS 1600 - Political Research Methods <br><br> Danilo Freire, Brown University"
    githubUsername = "danilofreire"
    accent = "brown"
    showBorder = true
    backgroundColor = "white"
    font = "Lato" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "python", "R"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/syllabus/"
    name = "Syllabus"
    weight = 1
    
[[menu.main]]
    url = "/assignments/"
    name = "Assignments"
    weight = 3

[[menu.main]]
    url = "/datasets/"
    name = "Datasets"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:danilofreire@brown.edu"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/danilofreire/pols1600"
    name = "github"
    weight = 2

